wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1680738616.068112
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.14.0
      8:
      - 5
asset:
  desc: null
  value:
    angular_damping: 0.0
    armature: 0.0
    collapse_fixed_joints: true
    default_dof_drive_mode: 3
    density: 0.001
    disable_gravity: false
    file: '{MINI_GYM_ROOT_DIR}/resources/robots/go1/urdf/go1.urdf'
    fix_base_link: false
    flip_visual_attachments: false
    foot_name: foot
    linear_damping: 0.0
    max_angular_velocity: 1000.0
    max_linear_velocity: 1000.0
    penalize_contacts_on:
    - thigh
    - calf
    replace_cylinder_with_capsule: true
    self_collisions: 0
    terminate_after_contacts_on:
    - base
    thickness: 0.01
commands:
  desc: null
  value:
    ang_vel_step: 0.3
    ang_vel_yaw:
    - -1.0
    - 1.0
    aux_reward_coef_range:
    - 0.0
    - 0.01
    balance_gait_distribution: true
    binary_phases: true
    body_height_cmd:
    - -0.25
    - 0.15
    body_pitch_range:
    - -0.4
    - 0.4
    body_roll_range:
    - -0.0
    - 0.0
    command_curriculum: true
    compliance_range:
    - 0.0
    - 0.01
    curriculum_seed: 100
    curriculum_type: RewardThresholdCurriculum
    distribution_update_extension_distance: 1
    distributional_commands: true
    exclusive_command_sampling: false
    exclusive_phase_offset: false
    footswing_height_range:
    - 0.03
    - 0.35
    gait_bound_cmd_range:
    - 0.0
    - 1.0
    gait_duration_cmd_range:
    - 0.5
    - 0.5
    gait_frequency_cmd_range:
    - 2.0
    - 4.0
    gait_interval_s: 10.0
    gait_offset_cmd_range:
    - 0.0
    - 1.0
    gait_phase_cmd_range:
    - 0.0
    - 1.0
    gaitwise_curricula: true
    global_reference: false
    heading:
    - -3.14
    - 3.14
    heading_command: false
    impulse_height_commands: false
    jump_duration_s: 0.1
    jump_height: 0.3
    jump_interval_s: 20.0
    limit_aux_reward_coef:
    - 0.0
    - 0.01
    limit_body_height:
    - -0.25
    - 0.15
    limit_body_pitch:
    - -0.4
    - 0.4
    limit_body_roll:
    - -0.0
    - 0.0
    limit_compliance:
    - 0.0
    - 0.01
    limit_footswing_height:
    - 0.03
    - 0.35
    limit_gait_bound:
    - 0.0
    - 1.0
    limit_gait_duration:
    - 0.5
    - 0.5
    limit_gait_frequency:
    - 2.0
    - 4.0
    limit_gait_offset:
    - 0.0
    - 1.0
    limit_gait_phase:
    - 0.0
    - 1.0
    limit_stance_length:
    - 0.35
    - 0.45
    limit_stance_width:
    - 0.1
    - 0.45
    limit_vel_x:
    - -5.0
    - 5.0
    limit_vel_y:
    - -0.6
    - 0.6
    limit_vel_yaw:
    - -5.0
    - 5.0
    lin_vel_step: 0.3
    lin_vel_x:
    - -1.0
    - 1.0
    lin_vel_y:
    - -0.6
    - 0.6
    lipschitz_threshold: 0.9
    max_forward_curriculum: 1.0
    max_reverse_curriculum: 1.0
    max_yaw_curriculum: 1.0
    num_ang_vel_bins: 30
    num_bins_aux_reward_coef: 1
    num_bins_body_height: 1
    num_bins_body_pitch: 1
    num_bins_body_roll: 1
    num_bins_compliance: 1
    num_bins_footswing_height: 1
    num_bins_gait_bound: 1
    num_bins_gait_duration: 1
    num_bins_gait_frequency: 1
    num_bins_gait_offset: 1
    num_bins_gait_phase: 1
    num_bins_stance_length: 1
    num_bins_stance_width: 1
    num_bins_vel_x: 21
    num_bins_vel_y: 1
    num_bins_vel_yaw: 21
    num_commands: 15
    num_lin_vel_bins: 30
    observe_accel: false
    pacing_offset: false
    resampling_time: 10
    stance_length_range:
    - 0.35
    - 0.45
    stance_width_range:
    - 0.1
    - 0.45
    subsample_gait: false
    vel_interval_s: 10.0
    yaw_command_curriculum: false
control:
  desc: null
  value:
    action_scale: 0.25
    control_type: actuator_net
    damping:
      joint: 0.5
    decimation: 4
    hip_scale_reduction: 0.5
    stiffness:
      joint: 20.0
curriculum_thresholds:
  desc: null
  value:
    tracking_ang_vel: 0.7
    tracking_contacts_shaped_force: 0.9
    tracking_contacts_shaped_vel: 0.9
    tracking_lin_vel: 0.8
domain_rand:
  desc: null
  value:
    Kd_factor_range:
    - 0.5
    - 1.5
    Kp_factor_range:
    - 0.8
    - 1.3
    added_mass_range:
    - -1.0
    - 3.0
    com_displacement_range:
    - -0.15
    - 0.15
    friction_range:
    - 0.1
    - 3.0
    gravity_impulse_duration: 0.99
    gravity_rand_interval_s: 8.0
    gravity_range:
    - -1.0
    - 1.0
    ground_friction_range:
    - 0.0
    - 0.0
    lag_timesteps: 6
    max_push_vel_xy: 0.5
    motor_offset_range:
    - -0.02
    - 0.02
    motor_strength_range:
    - 0.9
    - 1.1
    push_interval_s: 15
    push_robots: false
    rand_interval_s: 4
    randomize_Kd_factor: false
    randomize_Kp_factor: false
    randomize_base_mass: true
    randomize_com_displacement: false
    randomize_friction: true
    randomize_friction_indep: false
    randomize_gravity: true
    randomize_ground_friction: true
    randomize_lag_timesteps: true
    randomize_motor_offset: true
    randomize_motor_strength: true
    randomize_restitution: true
    randomize_rigids_after_start: false
    restitution: 0.5
    restitution_range:
    - 0.0
    - 0.4
    tile_height_curriculum: false
    tile_height_curriculum_step: 0.01
    tile_height_range:
    - -0.0
    - 0.0
    tile_height_update_interval: 1000000
env:
  desc: null
  value:
    all_agents_share: false
    debug_viz: false
    env_spacing: 3.0
    episode_length_s: 20
    num_actions: 12
    num_envs: 4000
    num_observation_history: 30
    num_observations: 70
    num_privileged_obs: 2
    num_recording_envs: 1
    num_scalar_observations: 70
    observe_clock_inputs: true
    observe_command: true
    observe_contact_states: false
    observe_gait_commands: true
    observe_height_command: false
    observe_imu: false
    observe_only_ang_vel: false
    observe_only_lin_vel: false
    observe_timing_parameter: false
    observe_two_prev_actions: true
    observe_vel: false
    observe_yaw: false
    priv_observe_Kd_factor: false
    priv_observe_Kp_factor: false
    priv_observe_base_mass: false
    priv_observe_body_height: false
    priv_observe_body_velocity: false
    priv_observe_clock_inputs: false
    priv_observe_com_displacement: false
    priv_observe_contact_forces: false
    priv_observe_contact_states: false
    priv_observe_desired_contact_states: false
    priv_observe_doubletime_clock_inputs: false
    priv_observe_dummy_variable: false
    priv_observe_foot_displacement: false
    priv_observe_foot_height: false
    priv_observe_friction: true
    priv_observe_friction_indep: false
    priv_observe_gravity: false
    priv_observe_gravity_transformed_foot_displacement: false
    priv_observe_gravity_transformed_motion: false
    priv_observe_ground_friction: false
    priv_observe_ground_friction_per_foot: false
    priv_observe_halftime_clock_inputs: false
    priv_observe_joint_friction: true
    priv_observe_motion: false
    priv_observe_motor_offset: false
    priv_observe_motor_strength: false
    priv_observe_restitution: true
    priv_observe_terrain_type: false
    privileged_future_horizon: 1
    record_video: true
    recording_height_px: 240
    recording_mode: COLOR
    recording_width_px: 360
    send_timeouts: true
init_state:
  desc: null
  value:
    ang_vel:
    - 0.0
    - 0.0
    - 0.0
    default_joint_angles:
      FL_calf_joint: -1.5
      FL_hip_joint: 0.1
      FL_thigh_joint: 0.8
      FR_calf_joint: -1.5
      FR_hip_joint: -0.1
      FR_thigh_joint: 0.8
      RL_calf_joint: -1.5
      RL_hip_joint: 0.1
      RL_thigh_joint: 1.0
      RR_calf_joint: -1.5
      RR_hip_joint: -0.1
      RR_thigh_joint: 1.0
    lin_vel:
    - 0.0
    - 0.0
    - 0.0
    pos:
    - 0.0
    - 0.0
    - 0.34
    rot:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
noise:
  desc: null
  value:
    add_noise: true
    noise_level: 1.0
noise_scales:
  desc: null
  value:
    ang_vel: 0.2
    contact_states: 0.05
    depth_image: 0.0
    dof_pos: 0.01
    dof_vel: 1.5
    friction_measurements: 0.0
    gravity: 0.05
    height_measurements: 0.1
    imu: 0.1
    lin_vel: 0.1
    rgb_image: 0.0
    segmentation_image: 0.0
normalization:
  desc: null
  value:
    Kd_factor_range:
    - 0.5
    - 1.5
    Kp_factor_range:
    - 0.8
    - 1.3
    added_mass_range:
    - -1.0
    - 3.0
    body_height_range:
    - 0.0
    - 0.6
    body_velocity_range:
    - -6.0
    - 6.0
    clip_actions: 10.0
    clip_observations: 100.0
    com_displacement_range:
    - -0.1
    - 0.1
    contact_force_range:
    - 0.0
    - 50.0
    contact_state_range:
    - 0.0
    - 1.0
    foot_height_range:
    - 0.0
    - 0.15
    friction_range:
    - 0
    - 1
    gravity_range:
    - -1.0
    - 1.0
    ground_friction_range:
    - 0
    - 1
    joint_friction_range:
    - 0.0
    - 0.7
    motion:
    - -0.01
    - 0.01
    motor_offset_range:
    - -0.05
    - 0.05
    motor_strength_range:
    - 0.9
    - 1.1
    restitution_range:
    - 0
    - 1.0
obs_scales:
  desc: null
  value:
    ang_vel: 0.25
    aux_reward_cmd: 1.0
    body_height_cmd: 2.0
    body_pitch_cmd: 0.3
    body_roll_cmd: 0.3
    compliance_cmd: 1.0
    depth_image: 1.0
    dof_pos: 1.0
    dof_vel: 0.05
    footswing_height_cmd: 0.15
    friction_measurements: 1.0
    gait_freq_cmd: 1.0
    gait_phase_cmd: 1.0
    height_measurements: 5.0
    imu: 0.1
    lin_vel: 2.0
    rgb_image: 1.0
    segmentation_image: 1.0
    stance_length_cmd: 1.0
    stance_width_cmd: 1.0
reward_scales:
  desc: null
  value:
    action_rate: -0.01
    action_smoothness_1: -0.1
    action_smoothness_2: -0.1
    ang_vel_xy: -0.001
    base_height: 0.0
    base_motion: 0.0
    collision: -5.0
    dof_acc: -2.5e-07
    dof_pos: -0.0
    dof_pos_limits: -10.0
    dof_vel: -0.0001
    energy: 0.0
    energy_expenditure: 0.0
    estimation_bonus: 0.0
    feet_air_time: 0.0
    feet_clearance: -0.0
    feet_clearance_cmd: -0.0
    feet_clearance_cmd_linear: -30.0
    feet_contact_forces: 0.0
    feet_impact_vel: -0.0
    feet_slip: -0.04
    feet_stumble: -0.0
    hop_symmetry: 0.0
    jump: 10.0
    lin_vel_z: -0.02
    orientation: 0.0
    orientation_control: -5.0
    raibert_heuristic: -10.0
    stand_still: -0.0
    survival: 0.0
    termination: -0.0
    torques: -0.0001
    tracking_ang_vel: 0.5
    tracking_contacts: 0.0
    tracking_contacts_shaped: 0.0
    tracking_contacts_shaped_force: 4.0
    tracking_contacts_shaped_vel: 4.0
    tracking_lin_vel: 1.0
    tracking_lin_vel_lat: 0.0
    tracking_lin_vel_long: 0.0
    tracking_stance_length: -0.0
    tracking_stance_width: -0.0
rewards:
  desc: null
  value:
    base_height_target: 0.3
    footswing_height: 0.09
    gait_force_sigma: 100.0
    gait_vel_sigma: 10.0
    kappa_gait_probs: 0.07
    max_contact_force: 100.0
    only_positive_rewards: false
    only_positive_rewards_ji22_style: true
    reward_container_name: CoRLRewards
    sigma_rew_neg: 0.02
    soft_dof_pos_limit: 0.9
    soft_dof_vel_limit: 1.0
    soft_torque_limit: 1.0
    terminal_body_height: 0.05
    terminal_body_ori: 1.6
    terminal_foot_height: -0.005
    tracking_sigma: 0.25
    tracking_sigma_lat: 0.25
    tracking_sigma_long: 0.25
    tracking_sigma_yaw: 0.25
    use_terminal_body_height: true
    use_terminal_foot_height: false
    use_terminal_roll_pitch: true
sim:
  desc: null
  value:
    dt: 0.005
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      bounce_threshold_velocity: 0.5
      contact_collection: 2
      contact_offset: 0.01
      default_buffer_size_multiplier: 5
      max_depenetration_velocity: 1.0
      max_gpu_contact_pairs: 8388608
      num_position_iterations: 4
      num_threads: 10
      num_velocity_iterations: 0
      rest_offset: 0.0
      solver_type: 1
    substeps: 1
    up_axis: 1
    use_gpu_pipeline: true
terrain:
  desc: null
  value:
    border_size: 0.0
    center_robots: true
    center_span: 4
    curriculum: false
    difficulty_scale: 1.0
    dynamic_friction: 1.0
    horizontal_scale: 0.1
    max_init_terrain_level: 5
    max_platform_height: 0.2
    measure_heights: false
    measured_points_x:
    - -0.8
    - -0.7
    - -0.6
    - -0.5
    - -0.4
    - -0.3
    - -0.2
    - -0.1
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    measured_points_y:
    - -0.5
    - -0.4
    - -0.3
    - -0.2
    - -0.1
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    mesh_type: trimesh
    min_init_terrain_level: 0
    num_cols: 30
    num_rows: 30
    restitution: 0.0
    selected: false
    slope_treshold: 0.75
    static_friction: 1.0
    teleport_robots: false
    teleport_thresh: 0.3
    terrain_kwargs: null
    terrain_length: 5.0
    terrain_noise_magnitude: 0.0
    terrain_proportions:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1.0
    terrain_smoothness: 0.005
    terrain_width: 5.0
    vertical_scale: 0.005
    x_init_offset: 0.0
    x_init_range: 0.2
    y_init_offset: 0.0
    y_init_range: 0.2
    yaw_init_range: 3.14
viewer:
  desc: null
  value:
    lookat:
    - 11.0
    - 5
    - 3.0
    pos:
    - 10
    - 0
    - 6
    ref_env: 0
